import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
<<<<<<< HEAD
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
=======
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
>>>>>>> a310f9b (Initial commit from Create Next App)
      >
        {children}
      </body>
    </html>
  );
}
