export const colleges = [
  {
    id: "uit1",
    name: "Uttaranchal University Of Technology (UIT)",
    location: "Dehradun, Uttarakhand",
    image: "/img/uit.jpeg",
    logo: "/img/uitLogo.jpg",
    rating: "4.5",
    accreditation: "AICTE +3",
    exams: "CAT",
    brochure: "/brochures/uttaranchal-university.pdf",
    desc: `The Uttaranchal Institute of Technology (UIT) is a leading
engineering institute located in Dehradun, Uttarakhand, and is a
constituent institute of Uttaranchal University. Established in
2006, the institute offers undergraduate and postgraduate programs
in various engineering and technology fields such as Computer
Science, Mechanical, Civil, and Aerospace Engineering. UIT focuses
on providing industry-oriented education through modern laboratories,
experienced faculty, and research-based learning. The institute also
promotes innovation, practical training, and strong placement
opportunities to prepare students for successful careers in the
technology sector.`,
    cutoff: [
      {
        course: "B.Tech Computer Science",  
        general: "85%",
        obc: "80%",
        sc: "75%",
        st: "70%",
      },
      {
        course: "B.Tech Mechanical Engineering",
        general: "80%",
        obc: "75%",
        sc: "70%",
        st: "65%",
      },
      {
        course: "B.Tech Civil Engineering",
        general: "78%",
        obc: "73%",
        sc: "68%",
        st: "63%",
      },
      {
        course: "MBA",
        general: "75%",
        obc: "70%",
        sc: "65%",
        st: "60%",
      },
      {
        course: "BCA",
        general: "70%",
        obc: "65%",
        sc: "60%",
        st: "55%",
      },
    ],
    placement: {
      highlightStats: {
        highestPackage: "1.5 Cr (International)",
        highestDomesticPackage: "60 LPA",
        averagePackage: "4.5 LPA",
        medianPackage: "3.75 LPA",
        placementRate: "80%",
        studentsPlaced: "2356+",
        companiesVisited: "750+",
        year: "2024-25",
      },
      branchWise: [
        {
          course: "B.Tech CSE / IT",
          avgPackage: "5.5 LPA",
          highestPackage: "1.5 Cr",
          placedStudents: "90%",
        },
        {
          course: "B.Tech Mechanical",
          avgPackage: "3.8 LPA",
          highestPackage: "12 LPA",
          placedStudents: "70%",
        },
        {
          course: "B.Tech Civil",
          avgPackage: "3.5 LPA",
          highestPackage: "10 LPA",
          placedStudents: "65%",
        },
        {
          course: "MBA",
          avgPackage: "4.0 LPA",
          highestPackage: "15 LPA",
          placedStudents: "75%",
        },
        {
          course: "BCA",
          avgPackage: "3.2 LPA",
          highestPackage: "8 LPA",
          placedStudents: "68%",
        },
      ],
      topRecruiters: [
        "Microsoft",
        "Google",
        "Adobe",
        "Amazon",
        "Wipro",
        "TCS",
        "Infosys",
        "Accenture",
        "Deloitte",
        "Capgemini",
        "IBM",
        "Nvidia",
        "Zscaler",
        "L&T Infotech",
        "Asian Paints",
        "Reliance",
      ],
      notablePlacements: [
        {
          name: "Abhinav Ankur",
          company: "Forma USA",
          package: "1.5 Cr",
          course: "B.Tech CSE",
        },
      ],
    },
    coursesAndFees: [
    // ─── UG COURSES ───
    {
      level: "UG",
      course: "B.Tech Computer Science & Engineering",
      duration: "4 Years",
      totalFees: "₹12.02 Lakhs",
      perYearFees: "₹3.00 Lakhs/Year",
      eligibility: "10+2 PCM with 60% | JEE Main / CUET",
      specializations: [
        "Cloud Computing",
        "Artificial Intelligence & ML",
        "Cyber Security",
        "Big Data Analytics",
        "Core CSE",
      ],
    },
    {
      level: "UG",
      course: "B.Tech Aerospace Engineering",
      duration: "4 Years",
      totalFees: "₹7.47 Lakhs",
      perYearFees: "₹1.87 Lakhs/Year",
      eligibility: "10+2 PCM with 60% | JEE Main / CUET",
      specializations: ["Aerospace Engineering"],
    },
    {
      level: "UG",
      course: "B.Tech Civil Engineering",
      duration: "4 Years",
      totalFees: "₹6.34 Lakhs",
      perYearFees: "₹1.59 Lakhs/Year",
      eligibility: "10+2 PCM with 60% | JEE Main / CUET",
      specializations: ["Civil Engineering"],
    },
    {
      level: "UG",
      course: "B.Tech Mechanical Engineering",
      duration: "4 Years",
      totalFees: "₹5.95 Lakhs",
      perYearFees: "₹1.49 Lakhs/Year",
      eligibility: "10+2 PCM with 60% | JEE Main / CUET",
      specializations: ["Mechanical Engineering"],
    },
    {
      level: "UG",
      course: "B.Tech (Lateral Entry)",
      duration: "3 Years",
      totalFees: "₹2.63 – 9.12 Lakhs",
      perYearFees: "₹87K – 3.04 Lakhs/Year",
      eligibility: "Diploma with 60%",
      specializations: [
        "CSE",
        "Aerospace Engineering",
        "Civil",
        "Mechanical",
      ],
    },
    {
      level: "UG",
      course: "BBA",
      duration: "3 Years",
      totalFees: "₹4.12 Lakhs",
      perYearFees: "₹1.37 Lakhs/Year",
      eligibility: "10+2 with 50% | Merit Based",
      specializations: [
        "General Management",
        "Human Resource Management",
        "Marketing",
        "Finance",
      ],
    },
    {
      level: "UG",
      course: "BCA",
      duration: "3 Years",
      totalFees: "₹72,000 (Online) / ₹4.20 Lakhs (Regular)",
      perYearFees: "₹24,000 – ₹1.40 Lakhs/Year",
      eligibility: "10+2 with 45%",
      specializations: ["General BCA"],
    },
    {
      level: "UG",
      course: "B.Com (Hons.)",
      duration: "3 Years",
      totalFees: "₹3.65 Lakhs",
      perYearFees: "₹1.22 Lakhs/Year",
      eligibility: "10+2 with 45% | CUET UG",
      specializations: ["Commerce (Hons.)"],
    },
    {
      level: "UG",
      course: "B.Sc (Nursing)",
      duration: "4 Years",
      totalFees: "₹10.20 Lakhs",
      perYearFees: "₹2.55 Lakhs/Year",
      eligibility: "10+2 PCB with 50% | NEET UG",
      specializations: ["Nursing"],
    },
    {
      level: "UG",
      course: "B.Sc (Hons.)",
      duration: "3 Years",
      totalFees: "₹5.05 Lakhs",
      perYearFees: "₹1.68 Lakhs/Year",
      eligibility: "10+2 with 50% | CUET UG",
      specializations: [
        "Physics",
        "Chemistry",
        "Mathematics",
        "Biotechnology",
        "Agriculture",
        "Microbiology",
        "Food Technology",
      ],
    },
    {
      level: "UG",
      course: "LLB (Hons.)",
      duration: "3 Years",
      totalFees: "₹4.13 Lakhs",
      perYearFees: "₹1.38 Lakhs/Year",
      eligibility: "Graduation with 45% | CLAT / Merit",
      specializations: ["Law"],
    },
    {
      level: "UG",
      course: "B.Pharma",
      duration: "4 Years",
      totalFees: "₹5.08 – 5.32 Lakhs",
      perYearFees: "₹1.27 – 1.33 Lakhs/Year",
      eligibility: "10+2 PCB/PCM with 50%",
      specializations: ["Pharmacy"],
    },
    {
      level: "UG",
      course: "BPT (Physiotherapy)",
      duration: "4.5 Years",
      totalFees: "₹6.75 Lakhs",
      perYearFees: "₹1.50 Lakhs/Year",
      eligibility: "10+2 PCB with 50%",
      specializations: ["Physiotherapy"],
    },

    // ─── PG COURSES ───
    {
      level: "PG",
      course: "MBA",
      duration: "2 Years",
      totalFees: "₹4.89 – 5.43 Lakhs",
      perYearFees: "₹2.44 – 2.72 Lakhs/Year",
      eligibility: "Graduation 50% | CAT / MAT / XAT / CMAT / CUET PG",
      specializations: [
        "Marketing",
        "Finance",
        "Human Resource Management",
        "Information Technology",
        "International Business",
        "Digital Marketing",
        "Logistics & Supply Chain",
      ],
    },
    {
      level: "PG",
      course: "M.Tech",
      duration: "2 Years",
      totalFees: "₹2.23 – 4.41 Lakhs",
      perYearFees: "₹1.12 – 2.20 Lakhs/Year",
      eligibility: "B.Tech with 60% | GATE / Merit",
      specializations: [
        "Computer Science & Engineering",
        "Construction Technology & Management",
      ],
    },
    {
      level: "PG",
      course: "MCA",
      duration: "2 Years",
      totalFees: "₹1.84 Lakhs",
      perYearFees: "₹92,000/Year",
      eligibility: "BCA / B.Sc CS with 50% | CUET PG",
      specializations: ["Computer Applications"],
    },
    {
      level: "PG",
      course: "M.Sc",
      duration: "2 Years",
      totalFees: "₹1.84 – 2.10 Lakhs",
      perYearFees: "₹92,000 – 1.05 Lakhs/Year",
      eligibility: "B.Sc with 50% | CUET PG",
      specializations: [
        "Biotechnology",
        "Microbiology",
        "Biochemistry",
        "Botany",
        "Zoology",
        "Chemistry",
        "Physics",
        "Mathematics",
      ],
    },
    {
      level: "PG",
      course: "M.Pharma",
      duration: "2 Years",
      totalFees: "₹2.60 Lakhs",
      perYearFees: "₹1.30 Lakhs/Year",
      eligibility: "B.Pharma with 55% | GPAT",
      specializations: ["Pharmacology", "Pharmaceutics"],
    },
    {
      level: "PG",
      course: "LLM",
      duration: "1 Year",
      totalFees: "₹1.10 Lakhs",
      perYearFees: "₹1.10 Lakhs/Year",
      eligibility: "LLB with 50%",
      specializations: ["Law"],
    },

    // ─── DIPLOMA ───
    {
      level: "Diploma",
      course: "D.Pharma",
      duration: "2 Years",
      totalFees: "₹1.20 – 1.40 Lakhs",
      perYearFees: "₹60,000 – 70,000/Year",
      eligibility: "10+2 PCB/PCM with 45%",
      specializations: ["Pharmacy"],
    },
    {
      level: "Diploma",
      course: "Diploma in Engineering (Polytechnic)",
      duration: "3 Years",
      totalFees: "₹1.87 Lakhs",
      perYearFees: "₹62,000/Year",
      eligibility: "10th Pass",
      specializations: [
        "Civil Engineering",
        "Mechanical Engineering",
        "Electrical Engineering",
      ],
    },

    // ─── DOCTORATE ───
    {
      level: "PhD",
      course: "Ph.D.",
      duration: "3-5 Years",
      totalFees: "₹3.60 – 4.28 Lakhs",
      perYearFees: "₹72,000 – 85,600/Year",
      eligibility: "PG with 55% | National Level Entrance / UU Entrance",
      specializations: [
        "Engineering",
        "Management",
        "Science",
        "Law",
        "Pharmacy",
        "Nursing",
      ],
    },
  ],
  },

  {
    id: "bfit",
    name: "BFIT",
    location: "Dehradun",
    image: "/img/dit.jpeg",
    logo: "/img/bfitLogo.png",
    rating: 4.5,
    brochure: "/brochures/bfit-university.pdf",
    desc: `BFIT Group of Institutions, located in Dehradun, Uttarakhand, is a well-known educational institute established in 2002. It offers undergraduate and postgraduate programs in fields such as Engineering, Management, Science, and Computer Applications. The institute focuses on practical learning, modern infrastructure, and industry-oriented training to help students develop professional skills and build successful careers.`,
    cutoff: [
      {
        course: "B.Tech Computer Science",
        general: "50%",
        obc: "50%",
        sc: "45%",
        st: "45%",
      },
      {
        course: "B.Tech Mechanical Engineering",
        general: "50%",
        obc: "50%",
        sc: "45%",
        st: "45%",
      },
      {
        course: "B.Tech Civil Engineering",
        general: "50%",
        obc: "50%",
        sc: "45%",
        st: "45%",
      },
      {
        course: "MBA",
        general: "50% (Graduation)",
        obc: "50% (Graduation)",
        sc: "45% (Graduation)",
        st: "45% (Graduation)",
      },
      {
        course: "BCA",
        general: "50%",
        obc: "50%",
        sc: "45%",
        st: "45%",
      },
    ],
    placement: {
      highlightStats: {
        highestPackage: "25 LPA",
        averagePackage: "5 LPA",
        lowestPackage: "3.9 LPA",
        placementRate: "70-84%",
        studentsPlaced: "450+",
        companiesVisited: "500+",
        year: "2024",
      },
      branchWise: [
        {
          course: "B.Tech CSE / IT",
          avgPackage: "6-7 LPA",
          highestPackage: "25 LPA",
          placedStudents: "80%",
        },
        {
          course: "B.Tech Mechanical",
          avgPackage: "4 LPA",
          highestPackage: "10 LPA",
          placedStudents: "65%",
        },
        {
          course: "MBA / BBA",
          avgPackage: "4.5 LPA",
          highestPackage: "12 LPA",
          placedStudents: "75%",
        },
        {
          course: "MCA / BCA",
          avgPackage: "4 LPA",
          highestPackage: "10 LPA",
          placedStudents: "70%",
        },
      ],
      topRecruiters: [
        "Infosys",
        "TCS",
        "Wipro",
        "IBM",
        "HP",
        "Tech Mahindra",
        "HDFC Bank",
        "Policy Bazaar",
        "Amazon",
        "Google",
        "Deloitte",
        "Britannia",
        "HCL",
        "Aanchal Dairy",
      ],
    },
    coursesAndFees: [
  // ─── UG COURSES ───
  {
     
    level: "UG",
    course: "B.Tech Computer Science & Engineering",
    duration: "4 Years",
    totalFees: "₹15.73 Lakhs",
    perYearFees: "₹2.32 Lakhs/Year (Tuition)",
    eligibility: "10+2 PCM with 50% | JEE Main / UKSEE",
    specializations: [
      "Core CSE",
      "Artificial Intelligence & ML",
      "Cloud Computing",
      "Cyber Security & Privacy",
      "Full Stack & DevOps",
      "Data Science",
    ],
  },
  {
    level: "UG",
    course: "B.Tech Information Technology",
    duration: "4 Years",
    totalFees: "₹9.52 Lakhs",
    perYearFees: "₹2.38 Lakhs/Year",
    eligibility: "10+2 PCM with 50% | JEE Main / UKSEE",
    specializations: ["Information Technology"],
  },
  {
    level: "UG",
    course: "B.Tech Electronics & Communication Engg.",
    duration: "4 Years",
    totalFees: "₹9.52 Lakhs",
    perYearFees: "₹2.38 Lakhs/Year",
    eligibility: "10+2 PCM with 50% | JEE Main / UKSEE",
    specializations: ["ECE"],
  },
  {
    level: "UG",
    course: "B.Tech Civil Engineering",
    duration: "4 Years",
    totalFees: "₹8.90 Lakhs",
    perYearFees: "₹2.23 Lakhs/Year",
    eligibility: "10+2 PCM with 50% | JEE Main / UKSEE",
    specializations: ["Civil Engineering"],
  },
  {
    level: "UG",
    course: "B.Tech Mechanical Engineering",
    duration: "4 Years",
    totalFees: "₹8.90 Lakhs",
    perYearFees: "₹2.23 Lakhs/Year",
    eligibility: "10+2 PCM with 50% | JEE Main / UKSEE",
    specializations: ["Mechanical Engineering"],
  },
  {
    level: "UG",
    course: "B.Arch (Architecture)",
    duration: "5 Years",
    totalFees: "₹14.08 Lakhs",
    perYearFees: "₹2.82 Lakhs/Year",
    eligibility: "10+2 with 45% | NATA",
    specializations: ["Architecture"],
  },
  {
    level: "UG",
    course: "BCA",
    duration: "3 Years",
    totalFees: "₹4.52 Lakhs",
    perYearFees: "₹1.51 Lakhs/Year",
    eligibility: "10+2 with 50% | Merit Based",
    specializations: ["Computer Applications"],
  },
  {
    level: "UG",
    course: "B.Sc (Hons.)",
    duration: "4 Years",
    totalFees: "₹4.35 – 5.87 Lakhs",
    perYearFees: "₹1.09 – 1.47 Lakhs/Year",
    eligibility: "10+2 with 50%",
    specializations: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Biotechnology",
      "Computer Science",
    ],
  },
  {
    level: "UG",
    course: "B.Des (Design)",
    duration: "4 Years",
    totalFees: "₹8.60 – 9.66 Lakhs",
    perYearFees: "₹2.15 – 2.42 Lakhs/Year",
    eligibility: "10+2 with 50% | UCEED / NID / Merit",
    specializations: [
      "Fashion Design",
      "Interior Design",
      "Graphic Design",
      "Product Design",
    ],
  },
  {
    level: "UG",
    course: "B.Pharma",
    duration: "4 Years",
    totalFees: "₹4.80 – 5.60 Lakhs",
    perYearFees: "₹1.20 – 1.40 Lakhs/Year",
    eligibility: "10+2 PCB/PCM with 50%",
    specializations: ["Pharmacy"],
  },
  {
    level: "UG",
    course: "B.Sc Nursing",
    duration: "4 Years",
    totalFees: "₹5.87 Lakhs",
    perYearFees: "₹1.47 Lakhs/Year",
    eligibility: "10+2 PCB with 50% | NEET UG",
    specializations: ["Nursing"],
  },
  {
    level: "UG",
    course: "BPT (Physiotherapy)",
    duration: "4.5 Years",
    totalFees: "₹5.40 Lakhs",
    perYearFees: "₹1.20 Lakhs/Year",
    eligibility: "10+2 PCB with 50%",
    specializations: ["Physiotherapy"],
  },
  {
    level: "UG",
    course: "BA (Hons.)",
    duration: "4 Years",
    totalFees: "₹4.35 Lakhs",
    perYearFees: "₹1.09 Lakhs/Year",
    eligibility: "10+2 with 50%",
    specializations: [
      "English",
      "Psychology",
      "Sociology",
      "Economics",
    ],
  },

  // ─── PG COURSES ───
  {
    level: "PG",
    course: "MBA",
    duration: "2 Years",
    totalFees: "₹8.47 Lakhs",
    perYearFees: "₹4.24 Lakhs/Year",
    eligibility: "Graduation 50% | CAT / MAT / XAT / CMAT / DUET",
    specializations: [
      "Finance",
      "Marketing",
      "Human Resource Management",
      "Operations",
      "Business Analytics",
      "International Business",
    ],
  },
  {
    level: "PG",
    course: "M.Tech",
    duration: "2 Years",
    totalFees: "₹1.85 – 3.50 Lakhs",
    perYearFees: "₹92,500 – 1.75 Lakhs/Year",
    eligibility: "B.Tech 60% | GATE / UGC-NET / Merit",
    specializations: [
      "Computer Science & Engineering",
      "Structural Engineering",
      "Power Systems",
    ],
  },
  {
    level: "PG",
    course: "MCA",
    duration: "2 Years",
    totalFees: "₹3.85 Lakhs",
    perYearFees: "₹1.93 Lakhs/Year",
    eligibility: "BCA / B.Sc CS 50% | CUET PG / Merit",
    specializations: ["Computer Applications"],
  },
  {
    level: "PG",
    course: "M.Sc",
    duration: "2 Years",
    totalFees: "₹2.10 – 3.20 Lakhs",
    perYearFees: "₹1.05 – 1.60 Lakhs/Year",
    eligibility: "B.Sc with 50%",
    specializations: [
      "Mathematics",
      "Physics",
      "Chemistry",
      "Biotechnology",
    ],
  },
  {
    level: "PG",
    course: "M.Des (Design)",
    duration: "2 Years",
    totalFees: "₹4.50 Lakhs",
    perYearFees: "₹2.25 Lakhs/Year",
    eligibility: "B.Des / B.Arch / B.Tech with 50%",
    specializations: ["Industrial Design", "Communication Design"],
  },
  {
    level: "PG",
    course: "M.Pharma",
    duration: "2 Years",
    totalFees: "₹2.80 Lakhs",
    perYearFees: "₹1.40 Lakhs/Year",
    eligibility: "B.Pharma 55% | GPAT",
    specializations: ["Pharmacology", "Pharmaceutics"],
  },

  // ─── DIPLOMA ───
  {
    level: "Diploma",
    course: "D.Pharma",
    duration: "2 Years",
    totalFees: "₹1.80 Lakhs",
    perYearFees: "₹90,000/Year",
    eligibility: "10+2 PCB/PCM with 45%",
    specializations: ["Pharmacy"],
  },
  {
    level: "Diploma",
    course: "Diploma in Engineering (After 10th)",
    duration: "3 Years",
    totalFees: "₹1.35 Lakhs",
    perYearFees: "₹45,000/Year",
    eligibility: "10th Pass",
    specializations: [
      "Civil Engineering",
      "Mechanical Engineering",
      "Electrical Engineering",
      "Computer Science",
    ],
  },

  // ─── DOCTORATE ───
  {
    level: "PhD",
    course: "Ph.D.",
    duration: "3-5 Years",
    totalFees: "₹3.31 – 4.94 Lakhs",
    perYearFees: "₹66,200 – 98,800/Year",
    eligibility: "PG with 55% | NET / GATE / University Entrance",
    specializations: [
      "Engineering",
      "Management",
      "Science",
      "Pharmacy",
      "Design",
      "Architecture",
    ],
  },
],
  },

  {
    id: "jbit",
    name: "JBIT College",
    location: "Dehradun",
    image: "/img/jbit.jpeg",
    logo: "/img/jbitLogo.jpg",
    rating: 4.5,
    brochure: "/brochures/brochure_jbit_web.pdf",
    desc: `JB Institute of Technology (JBIT), located in Dehradun, Uttarakhand, is a well-known private engineering college established in 2009. The institute offers undergraduate programs in various engineering disciplines such as Computer Science, Mechanical, Civil, and Electrical Engineering. JBIT focuses on quality technical education, modern laboratories, experienced faculty, and industry-oriented training to prepare students for professional careers in the technology sector.`,
    cutoff: [
      {
        course: "B.Tech Computer Science",
        general: "45% (PCM)",
        obc: "45% (PCM)",
        sc: "40% (PCM)",
        st: "40% (PCM)",
      },
      {
        course: "B.Tech Mechanical Engineering",
        general: "45% (PCM)",
        obc: "45% (PCM)",
        sc: "40% (PCM)",
        st: "40% (PCM)",
      },
      {
        course: "B.Tech Civil Engineering",
        general: "45% (PCM)",
        obc: "45% (PCM)",
        sc: "40% (PCM)",
        st: "40% (PCM)",
      },
      {
        course: "MBA",
        general: "50% (Graduation)",
        obc: "50% (Graduation)",
        sc: "45% (Graduation)",
        st: "45% (Graduation)",
      },
      {
        course: "BCA",
        general: "45%",
        obc: "45%",
        sc: "40%",
        st: "40%",
      },
    ],
    placement: {
      highlightStats: {
        highestPackage: "30 LPA",
        averagePackage: "4-4.4 LPA",
        lowestPackage: "2.5 LPA",
        placementRate: "83%",
        studentsPlaced: "257+",
        companiesVisited: "150+ MNCs",
        year: "2024",
      },
      branchWise: [
        {
          course: "B.Tech CSE / IT",
          avgPackage: "9.2 LPA",
          highestPackage: "30 LPA",
          placedStudents: "85%",
        },
        {
          course: "B.Tech Mechanical",
          avgPackage: "3-5 LPA",
          highestPackage: "12 LPA",
          placedStudents: "70%",
        },
        {
          course: "B.Tech ECE",
          avgPackage: "3.5 LPA",
          highestPackage: "10 LPA",
          placedStudents: "72%",
        },
        {
          course: "MBA",
          avgPackage: "4 LPA",
          highestPackage: "8 LPA",
          placedStudents: "75%",
        },
        {
          course: "Diploma",
          avgPackage: "2.5 LPA",
          highestPackage: "5 LPA",
          placedStudents: "100%",
        },
      ],
      topRecruiters: [
        "TCS",
        "Wipro",
        "Infosys",
        "HCL",
        "Tech Mahindra",
        "Cognizant",
        "Amazon",
        "IBM",
        "Oracle",
        "Accenture",
        "Ericsson",
        "Havells",
        "Birla Soft",
        "Global Logic",
        "Genpact",
        "eClerx",
        "Bridgestone",
        "IndiaMart",
      ],
    },
    coursesAndFees: [
  // ─── B.TECH ───
  {
    level: "UG",
    course: "B.Tech Computer Science & Engineering",
    duration: "4 Years",
    totalFees: "₹3.60 – 4.00 Lakhs",
    perYearFees: "₹90,000 – 1.00 Lakhs/Year",
    eligibility: "10+2 PCM (45%) | JEE Main / Merit",
  },
  {
    level: "UG",
    course: "B.Tech Mechanical Engineering",
    duration: "4 Years",
    totalFees: "₹3.20 – 3.60 Lakhs",
    perYearFees: "₹80,000 – 90,000/Year",
    eligibility: "10+2 PCM (45%)",
  },
  {
    level: "UG",
    course: "B.Tech Civil Engineering",
    duration: "4 Years",
    totalFees: "₹3.20 – 3.60 Lakhs",
    perYearFees: "₹80,000 – 90,000/Year",
    eligibility: "10+2 PCM (45%)",
  },

  // ─── BCA / BBA ───
  {
    level: "UG",
    course: "BCA",
    duration: "3 Years",
    totalFees: "₹1.50 – 1.80 Lakhs",
    perYearFees: "₹50,000 – 60,000/Year",
    eligibility: "10+2 (45%)",
  },
  {
    level: "UG",
    course: "BBA",
    duration: "3 Years",
    totalFees: "₹1.50 – 1.80 Lakhs",
    perYearFees: "₹50,000 – 60,000/Year",
    eligibility: "10+2 (45%)",
  },

  // ─── PG COURSES ───
  {
    level: "PG",
    course: "MBA",
    duration: "2 Years",
    totalFees: "₹2.20 – 2.60 Lakhs",
    perYearFees: "₹1.10 – 1.30 Lakhs/Year",
    eligibility: "Graduation (50%) | CAT / MAT / Merit",
  },
  {
    level: "PG",
    course: "MCA",
    duration: "2 Years",
    totalFees: "₹1.40 – 1.80 Lakhs",
    perYearFees: "₹70,000 – 90,000/Year",
    eligibility: "BCA / Graduation with Maths",
  },

  // ─── DIPLOMA ───
  {
    level: "Diploma",
    course: "Diploma in Engineering",
    duration: "3 Years",
    totalFees: "₹1.00 – 1.30 Lakhs",
    perYearFees: "₹35,000 – 45,000/Year",
    eligibility: "10th Pass",
  }
]
  },

  {
    id: "Dbuu",
    name: "Dev bhoomi uttarakhand University",
    location: "Dehradun",
    image: "/img/Devbhoomi.pg.webp",
    logo: "/img/DevLogo.pg.png",
    rating: 4.2,
    brochure: "/brochures/DBUU-Brochure.pdf",
    desc: "Dev Bhoomi Uttarakhand University (DBUU) is a well-known private university located in Dehradun, surrounded by beautiful greenery and a peaceful environment. The university is recognized by UGC and several professional bodies, ensuring quality education and national-level credibility.",
    cutoff: [
      {
        course: "B.Tech Computer Science",
        general: "50% (PCM)",
        obc: "50% (PCM)",
        sc: "45% (PCM)",
        st: "45% (PCM)",
      },
      {
        course: "B.Tech Mechanical Engineering",
        general: "50% (PCM)",
        obc: "50% (PCM)",
        sc: "45% (PCM)",
        st: "45% (PCM)",
      },
      {
        course: "B.Tech Civil Engineering",
        general: "50% (PCM)",
        obc: "50% (PCM)",
        sc: "45% (PCM)",
        st: "45% (PCM)",
      },
      {
        course: "MBA",
        general: "50% (Graduation)",
        obc: "50% (Graduation)",
        sc: "45% (Graduation)",
        st: "45% (Graduation)",
      },
      {
        course: "BCA",
        general: "50%",
        obc: "50%",
        sc: "45%",
        st: "45%",
      },
    ],
    placement: {
      highlightStats: {
        highestPackage: "43 LPA",
        averagePackage: "6 LPA",
        lowestPackage: "3 LPA",
        placementRate: "80%",
        studentsPlaced: "14,500+ (cumulative)",
        companiesVisited: "850+",
        year: "2024-25",
      },
      branchWise: [
        {
          course: "B.Tech Mechanical Engineering",
          avgPackage: "5 LPA",
          highestPackage: "40 LPA",
          placedStudents: "75%",
          note: "Kamlesh Singh – 40 LPA at Robbins",
        },
        {
          course: "B.Tech EEE",
          avgPackage: "5 LPA",
          highestPackage: "35 LPA",
          placedStudents: "75%",
          note: "Murli Manohar – 35 LPA at Robbins",
        },
        {
          course: "B.Tech CSE / IT",
          avgPackage: "6-7 LPA",
          highestPackage: "14 LPA",
          placedStudents: "80%",
        },
        {
          course: "MBA",
          avgPackage: "5 LPA",
          highestPackage: "27 LPA",
          placedStudents: "80%",
        },
        {
          course: "BCA / MCA",
          avgPackage: "4 LPA",
          highestPackage: "10 LPA",
          placedStudents: "70%",
        },
      ],
      topRecruiters: [
        "Adobe",
        "TCS",
        "Wipro",
        "IBM",
        "Infosys",
        "Amazon",
        "Accenture",
        "Deloitte",
        "HCL",
        "Capgemini",
        "Federal Bank",
        "HDFC Bank",
        "Zscaler",
        "Decathlon",
        "Daffodil",
        "Oracle",
        "Cognizant",
        "Tech Mahindra",
      ],
      notablePlacements: [
        {
          name: "Kamlesh Singh",
          company: "Robbins",
          package: "40 LPA",
          course: "B.Tech ME",
        },
        {
          name: "Murli Manohar",
          company: "Robbins",
          package: "35 LPA",
          course: "B.Tech EEE",
        },
      ],
    },
    coursesAndFees: [
  // ─── B.TECH ───
  {
    level: "UG",
    course: "B.Tech",
    duration: "4 Years",
    totalFees: "₹5.5 – 9.0 Lakhs",
    perYearFees: "₹1.3 – 1.9 Lakhs/Year",
    eligibility: "10+2 PCM (45–55%)",
  },

  // ─── BCA / BBA ───
  {
    level: "UG",
    course: "BCA",
    duration: "3 Years",
    totalFees: "₹4.0 – 5.6 Lakhs",
    perYearFees: "₹1.1 – 1.9 Lakhs/Year",
    eligibility: "10+2 (50%)",
  },
  {
    level: "UG",
    course: "BBA",
    duration: "3 Years",
    totalFees: "₹4.0 – 5.6 Lakhs",
    perYearFees: "₹1.1 – 1.9 Lakhs/Year",
    eligibility: "10+2 (50–55%)",
  },

  // ─── B.SC / OTHER UG ───
  {
    level: "UG",
    course: "B.Sc",
    duration: "3-4 Years",
    totalFees: "₹2.8 – 4.8 Lakhs",
    perYearFees: "₹75,000 – 1.2 Lakhs/Year",
    eligibility: "10+2",
  },
  {
    level: "UG",
    course: "B.Pharm",
    duration: "4 Years",
    totalFees: "₹6.5 – 7.0 Lakhs",
    perYearFees: "₹1.5 – 1.7 Lakhs/Year",
    eligibility: "10+2 PCB/PCM",
  },

  // ─── PG COURSES ───
  {
    level: "PG",
    course: "MBA",
    duration: "2 Years",
    totalFees: "₹3.5 – 4.0 Lakhs",
    perYearFees: "₹1.8 – 2.0 Lakhs/Year",
    eligibility: "Graduation (50%)",
  },
  {
    level: "PG",
    course: "MCA",
    duration: "2 Years",
    totalFees: "₹2.5 – 2.8 Lakhs",
    perYearFees: "₹1.2 – 1.4 Lakhs/Year",
    eligibility: "Graduation with Maths",
  },
  {
    level: "PG",
    course: "M.Tech",
    duration: "2 Years",
    totalFees: "₹2.2 – 3.0 Lakhs",
    perYearFees: "₹1.1 – 1.5 Lakhs/Year",
    eligibility: "B.Tech",
  }
]
  },

  {
    id: "GRU",
    name: "Graphic Era University",
    location: "Dehradun",
    image: "/img/Graphic.png",
    logo: "/img/GraphicLogo.png",
    rating: 4.5,
    brochure: "/brochures/graphic_brochure.pdf",
    desc: "Graphic Era University is a reputed private university located in Dehradun, known for its quality education and modern infrastructure. It is recognized by UGC and offers a wide range of courses in Engineering, Management, Computer Applications, and other fields. The university focuses on practical learning, experienced faculty, and strong placement support, helping students build successful careers.",
    cutoff: [
      {
        course: "B.Tech Computer Science",
        general: "55% (PCM) + JEE ~70 percentile",
        obc: "50% (PCM)",
        sc: "45% (PCM)",
        st: "45% (PCM)",
      },
      {
        course: "B.Tech Mechanical Engineering",
        general: "55% (PCM) + JEE ~60 percentile",
        obc: "50% (PCM)",
        sc: "45% (PCM)",
        st: "45% (PCM)",
      },
      {
        course: "B.Tech Civil Engineering",
        general: "55% (PCM) + JEE ~55 percentile",
        obc: "50% (PCM)",
        sc: "45% (PCM)",
        st: "45% (PCM)",
      },
      {
        course: "MBA",
        general: "50% (Graduation) + CAT/MAT ~65-75 percentile",
        obc: "50% (Graduation)",
        sc: "45% (Graduation)",
        st: "45% (Graduation)",
      },
      {
        course: "BCA",
        general: "60%",
        obc: "55%",
        sc: "50%",
        st: "50%",
      },
    ],
    placement: {
      highlightStats: {
        highestPackage: "61.99 LPA",
        averagePackage: "7.5 LPA",
        medianPackage: "6.5 LPA",
        placementRate: "80%",
        studentsPlaced: "2300+",
        companiesVisited: "250+",
        year: "2024-25",
      },
      branchWise: [
        {
          course: "B.Tech CSE",
          avgPackage: "24.19 LPA",
          highestPackage: "61.99 LPA",
          placedStudents: "159",
          note: "Altassin – 61.99 LPA | Amazon – 47.88 LPA (32 offers)",
        },
        {
          course: "B.Tech Computer Engineering",
          avgPackage: "23.29 LPA",
          highestPackage: "47.88 LPA",
          placedStudents: "80%",
        },
        {
          course: "B.Tech Mechanical / EE",
          avgPackage: "5 LPA",
          highestPackage: "16.67 LPA",
          placedStudents: "70%",
        },
        {
          course: "MBA",
          avgPackage: "5 LPA",
          highestPackage: "16 LPA",
          placedStudents: "80-85%",
        },
        {
          course: "MBA (AI & DS)",
          avgPackage: "12.8 LPA",
          highestPackage: "15.4 LPA",
          placedStudents: "75%",
        },
        {
          course: "MCA",
          avgPackage: "10.75 LPA",
          highestPackage: "12 LPA",
          placedStudents: "70%",
        },
        {
          course: "BBA",
          avgPackage: "4-5 LPA",
          highestPackage: "8 LPA",
          placedStudents: "50%",
        },
      ],
      topRecruiters: [
        "Google",
        "Amazon",
        "Microsoft",
        "Adobe",
        "Flipkart",
        "Walmart",
        "DE Shaw",
        "Visa",
        "JP Morgan",
        "Intuit",
        "PayPal",
        "Myntra",
        "TCS",
        "Wipro",
        "Infosys",
        "Accenture",
        "Deloitte",
        "KPMG",
        "Zscaler",
        "HCL",
        "Tech Mahindra",
        "Capgemini",
      ],
      notablePlacements: [
        {
          name: "BTech CSE Student",
          company: "Altassin",
          package: "61.99 LPA",
          course: "B.Tech CSE",
        },
        {
          name: "BTech CSE Student",
          company: "Google",
          package: "54.03 LPA",
          course: "B.Tech CSE",
          year: "2024",
        },
      ],
    },
    coursesAndFees: [
  // ─── B.TECH ───
  {
    level: "UG",
    course: "B.Tech",
    duration: "4 Years",
    totalFees: "₹10.0 – 14.0 Lakhs",
    perYearFees: "₹2.5 – 3.5 Lakhs/Year",
    eligibility: "10+2 PCM (60%) | JEE Main / Merit",
  },

  // ─── BCA / BBA ───
  {
    level: "UG",
    course: "BCA",
    duration: "3 Years",
    totalFees: "₹4.5 – 6.0 Lakhs",
    perYearFees: "₹1.5 – 2.0 Lakhs/Year",
    eligibility: "10+2 (50–60%)",
  },
  {
    level: "UG",
    course: "BBA",
    duration: "3 Years",
    totalFees: "₹5.0 – 6.5 Lakhs",
    perYearFees: "₹1.6 – 2.2 Lakhs/Year",
    eligibility: "10+2 (50–60%)",
  },

  // ─── B.SC / OTHER UG ───
  {
    level: "UG",
    course: "B.Sc",
    duration: "3 Years",
    totalFees: "₹3.0 – 5.0 Lakhs",
    perYearFees: "₹1.0 – 1.7 Lakhs/Year",
    eligibility: "10+2",
  },
  {
    level: "UG",
    course: "B.Com (Hons.)",
    duration: "3 Years",
    totalFees: "₹3.5 – 4.5 Lakhs",
    perYearFees: "₹1.1 – 1.5 Lakhs/Year",
    eligibility: "10+2",
  },

  // ─── PG COURSES ───
  {
    level: "PG",
    course: "MBA",
    duration: "2 Years",
    totalFees: "₹7.0 – 9.0 Lakhs",
    perYearFees: "₹3.5 – 4.5 Lakhs/Year",
    eligibility: "Graduation (50%) | CAT / MAT / XAT",
  },
  {
    level: "PG",
    course: "MCA",
    duration: "2 Years",
    totalFees: "₹3.0 – 4.5 Lakhs",
    perYearFees: "₹1.5 – 2.2 Lakhs/Year",
    eligibility: "BCA / Graduation with Maths",
  },
  {
    level: "PG",
    course: "M.Tech",
    duration: "2 Years",
    totalFees: "₹2.5 – 4.0 Lakhs",
    perYearFees: "₹1.2 – 2.0 Lakhs/Year",
    eligibility: "B.Tech",
  }
]
  },

  {
    id: "SssMc",
    name: "Shubharti university",
    location: "Dehradun",
    image: "/img/SssMc.jpg",
    logo: "/img/SssmcLogo.pg.jpg",
    rating: 4.3,
    brochure: "/brochures/subharti_brochure.pdf",
    desc: "Ras Bihari Bose Subharti University is a private university in Dehradun, established in 2016, known for its eco-friendly campus and decent infrastructure. It offers a variety of courses in fields like Science, Management, Pharmacy, Nursing, and Arts. The university focuses on practical learning, basic facilities, and skill development, making it a moderate option for students looking for affordable education in Dehradun.",
    cutoff: [
      {
        course: "B.Tech Computer Science",
        general: "60%",
        obc: "55%",
        sc: "50%",
        st: "50%",
      },
      {
        course: "B.Tech Mechanical Engineering",
        general: "55%",
        obc: "50%",
        sc: "45%",
        st: "45%",
      },
      {
        course: "B.Tech Civil Engineering",
        general: "55%",
        obc: "50%",
        sc: "45%",
        st: "45%",
      },
      {
        course: "MBA",
        general: "50% (Graduation)",
        obc: "45% (Graduation)",
        sc: "40% (Graduation)",
        st: "40% (Graduation)",
      },
      {
        course: "BCA",
        general: "50%",
        obc: "50%",
        sc: "45%",
        st: "40%",
      },
    ],
    placement: {
      note: "Medical college — placements are in the form of internships, residency, hospital jobs & PG admissions.",
      highlightStats: {
        internshipType:
          "Mandatory 1-year rotating internship at KKB Memorial Hospital",
        pgAdmissionRate: "Students appear for NEET-PG / INI-CET",
        placementRate: "Hospital-based clinical placements",
        hospitalBeds: "300+ bed attached teaching hospital",
        year: "2024",
      },
      branchWise: [
        {
          course: "MBBS",
          avgSalary: "₹50K–₹1.2L/month (Junior Resident / MO)",
          highestSalary: "PG specialists: ₹2L+/month",
          outcome: "Internship → NEET-PG / Govt Job / Private Hospital",
        },
        {
          course: "B.Sc MLT / Optometry / MRIT",
          avgSalary: "₹2–4 LPA",
          highestSalary: "₹6 LPA",
          outcome: "Labs, Hospitals, Diagnostic Centres",
        },
        {
          course: "BPT (Physiotherapy)",
          avgSalary: "₹2.5–4 LPA",
          highestSalary: "₹6 LPA",
          outcome: "Rehab centres, Hospitals, Private Practice",
        },
        {
          course: "M.Sc (Medical Anatomy / Biochemistry)",
          avgSalary: "₹3–5 LPA",
          highestSalary: "₹8 LPA",
          outcome: "Research, Teaching, Hospital Labs",
        },
      ],
      topRecruiters: [
        "KKB Memorial Hospital",
        "Doon Hospital",
        "Max Hospital",
        "Fortis Hospital",
        "Government Medical Colleges",
        "Diagnostic Labs",
        "AIIMS (PG)",
        "Private Clinics",
      ],
    },
    coursesAndFees: [
  // ─── MEDICAL / HEALTH ───
  {
    level: "UG",
    course: "MBBS",
    duration: "5.5 Years",
    totalFees: "₹23 – 27 Lakhs",
    perYearFees: "₹5 – 6 Lakhs/Year",
    eligibility: "10+2 PCB | NEET",
  },
  {
    level: "UG",
    course: "B.Sc Nursing",
    duration: "4 Years",
    totalFees: "₹4.5 – 5.0 Lakhs",
    perYearFees: "₹1.1 – 1.3 Lakhs/Year",
    eligibility: "10+2 PCB",
  },
  {
    level: "UG",
    course: "BPT (Physiotherapy)",
    duration: "4 Years",
    totalFees: "₹2.8 Lakhs",
    perYearFees: "₹70,000/Year",
    eligibility: "10+2",
  },

  // ─── PHARMACY / PARAMEDICAL ───
  {
    level: "UG",
    course: "D.Pharm",
    duration: "2 Years",
    totalFees: "₹1.3 – 1.4 Lakhs",
    perYearFees: "₹65,000 – 70,000/Year",
    eligibility: "10+2 PCB/PCM",
  },
  {
    level: "UG",
    course: "BNYS",
    duration: "5 Years",
    totalFees: "₹3.9 – 4.0 Lakhs",
    perYearFees: "₹80,000 – 1.0 Lakhs/Year",
    eligibility: "10+2",
  },

  // ─── GENERAL COURSES ───
  {
    level: "UG",
    course: "BCA",
    duration: "3 Years",
    totalFees: "₹1.5 Lakhs",
    perYearFees: "₹50,000/Year",
    eligibility: "10+2",
  },
  {
    level: "UG",
    course: "B.Com",
    duration: "3 Years",
    totalFees: "₹35,000 – 40,000",
    perYearFees: "₹12,000 – 15,000/Year",
    eligibility: "10+2",
  },

  // ─── PG COURSES ───
  {
    level: "PG",
    course: "MCA",
    duration: "2 Years",
    totalFees: "₹1.0 – 1.1 Lakhs",
    perYearFees: "₹50,000 – 55,000/Year",
    eligibility: "Graduation",
  },
  {
    level: "PG",
    course: "MBA",
    duration: "2 Years",
    totalFees: "₹2.5 – 2.7 Lakhs",
    perYearFees: "₹1.2 – 1.3 Lakhs/Year",
    eligibility: "Graduation",
  },
  {
    level: "PG",
    course: "M.Sc",
    duration: "2 Years",
    totalFees: "₹70,000 – 80,000",
    perYearFees: "₹35,000 – 40,000/Year",
    eligibility: "B.Sc",
  }
]
  },
  {
    id: "devpg",
    name: " DAV (PG)",
    location: "Dehradun",
    image: "/img/Dav.jpg",
    logo: "/img/DavLogo.png",
    brochure: "/brochures/DAV_brochure.pdf",
    rating: 4.5,
    desc: "DAV (PG) College is one of the oldest and well-known government colleges in Dehradun, affiliated with HNB Garhwal University. It offers courses in Arts, Science, Commerce, Law, and Education with affordable fees, making it a popular choice among local students. The college has decent academics, basic infrastructure, and a focus on traditional degree programs, but placements and modern facilities are limited compared to private universities.",
    cutoff: [
      {
        course: "B.Sc (PCM / Computer Science)",
        general: "75%",
        obc: "70%",
        sc: "65%",
        st: "60%",
      },
      {
        course: "B.A",
        general: "65%",
        obc: "60%",
        sc: "55%",
        st: "50%",
      },
      {
        course: "B.Com",
        general: "70%",
        obc: "65%",
        sc: "60%",
        st: "55%",
      },
      {
        course: "M.A",
        general: "50% (Graduation)",
        obc: "50% (Graduation)",
        sc: "45% (Graduation)",
        st: "45% (Graduation)",
      },
      {
        course: "M.Com",
        general: "50% (Graduation)",
        obc: "50% (Graduation)",
        sc: "45% (Graduation)",
        st: "45% (Graduation)",
      },
    ],
    placement: {
      highlightStats: {
        highestPackage: "35 LPA",
        averagePackage: "2-3 LPA",
        placementRate: "80%",
        studentsPlaced: "200+",
        companiesVisited: "20+",
        year: "2024",
        note: "Arts/Science/Commerce college — placements mainly in non-tech sectors",
      },
      branchWise: [
        {
          course: "M.Sc (Science)",
          avgPackage: "3-4 LPA",
          highestPackage: "35 LPA",
          placedStudents: "70%",
          roles: "Research Scientist, Lab Analyst, Biologist",
        },
        {
          course: "B.Sc",
          avgPackage: "2-3 LPA",
          highestPackage: "6 LPA",
          placedStudents: "65%",
          roles: "Lab Technician, Data Analyst, Forensic Scientist",
        },
        {
          course: "B.Com / M.Com",
          avgPackage: "2-3 LPA",
          highestPackage: "5 LPA",
          placedStudents: "70%",
          roles: "Accountant, Finance Executive, Banking",
        },
        {
          course: "BA / MA",
          avgPackage: "2-2.5 LPA",
          highestPackage: "4 LPA",
          placedStudents: "60%",
          roles: "Teaching, Journalism, Civil Services",
        },
        {
          course: "LLB",
          avgPackage: "3 LPA",
          highestPackage: "6 LPA",
          placedStudents: "65%",
          roles: "Legal Associate, Court Practice, Govt. Law",
        },
      ],
      topRecruiters: [
        "TCS",
        "Wipro",
        "Cipla",
        "HDFC Bank",
        "Toshiba",
        "Talent Port",
        "Sky Wings",
        "Career Media",
        "Tata Motors",
        "Adani",
        "Reliance",
        "Infosys",
      ],
    },
    coursesAndFees: [
  // ─── UG COURSES ───
  {
    level: "UG",
    course: "BA",
    duration: "3 Years",
    totalFees: "₹6,000 – 10,000",
    perYearFees: "₹2,000 – 3,500/Year",
    eligibility: "10+2",
  },
  {
    level: "UG",
    course: "B.Sc",
    duration: "3 Years",
    totalFees: "₹9,000 – 15,000",
    perYearFees: "₹3,000 – 5,000/Year",
    eligibility: "10+2 (Science)",
  },
  {
    level: "UG",
    course: "B.Com",
    duration: "3 Years",
    totalFees: "₹7,000 – 12,000",
    perYearFees: "₹2,500 – 4,000/Year",
    eligibility: "10+2 (Commerce/Any)",
  },

  // ─── PG COURSES ───
  {
    level: "PG",
    course: "MA",
    duration: "2 Years",
    totalFees: "₹4,000 – 8,000",
    perYearFees: "₹2,000 – 4,000/Year",
    eligibility: "Graduation",
  },
  {
    level: "PG",
    course: "M.Sc",
    duration: "2 Years",
    totalFees: "₹6,000 – 12,000",
    perYearFees: "₹3,000 – 6,000/Year",
    eligibility: "B.Sc",
  },
  {
    level: "PG",
    course: "M.Com",
    duration: "2 Years",
    totalFees: "₹5,000 – 10,000",
    perYearFees: "₹2,500 – 5,000/Year",
    eligibility: "B.Com",
  }
]
  },

  {
    id: "Nav",
    name: "NAV Chetna college",
    location: "Dehradun",
    image: "/img/Nav.jpg",
    logo: "/img/NavLogo.png",
    rating: 4.1,
    brochure: "/brochures/nav-university-Brochure.pdf",
    desc: "Nav Chetna College is a private college in Dehradun, established around 2005, offering undergraduate and postgraduate courses in Arts, Science, Commerce, and some professional programs. It is affiliated with state universities and focuses on basic academic learning with practical exposure.",
    cutoff: [
      {
        course: "B.Sc (PCM / Computer Science)",
        general: "50%",
        obc: "50%",
        sc: "45%",
        st: "45%",
      },
      {
        course: "B.A",
        general: "45%",
        obc: "45%",
        sc: "40%",
        st: "40%",
      },
      {
        course: "B.Com",
        general: "50%",
        obc: "45%",
        sc: "40%",
        st: "40%",
      },
      {
        course: "M.A",
        general: "50% (Graduation)",
        obc: "50% (Graduation)",
        sc: "45% (Graduation)",
        st: "45% (Graduation)",
      },
      {
        course: "BCA",
        general: "50%",
        obc: "45%",
        sc: "40%",
        st: "40%",
      },
    ],
    placement: {
      highlightStats: {
        highestPackage: "5.75 LPA",
        averagePackage: "4.3 LPA",
        placementRate: "77%",
        studentsPlaced: "60 out of 78 registered",
        companiesVisited: "15+",
        year: "2021-22",
        note: "Arts/Commerce/Management college — non-tech sector placements",
      },
      branchWise: [
        {
          course: "BBA",
          avgPackage: "3.5-4.5 LPA",
          highestPackage: "5.75 LPA",
          placedStudents: "75%",
          roles: "Sales Executive, Marketing Manager, HR Executive",
        },
        {
          course: "BCA",
          avgPackage: "3-4 LPA",
          highestPackage: "5 LPA",
          placedStudents: "70%",
          roles: "IT Support, Web Developer, Data Entry",
        },
        {
          course: "B.Com",
          avgPackage: "2.5-3.5 LPA",
          highestPackage: "4.5 LPA",
          placedStudents: "70%",
          roles: "Accountant, Finance Executive, Banking",
        },
        {
          course: "BA / MA",
          avgPackage: "2-3 LPA",
          highestPackage: "4 LPA",
          placedStudents: "60%",
          roles: "Teaching, Content Writing, Civil Services Prep",
        },
        {
          course: "B.Sc Nursing / D.Pharm",
          avgPackage: "2.5-4 LPA",
          highestPackage: "5 LPA",
          placedStudents: "80%",
          roles: "Staff Nurse, Pharmacist, Hospital Care",
        },
      ],
      topRecruiters: [
        "Asian Paints",
        "Havells",
        "UltraTech Cement",
        "ACC Limited",
        "USHA",
        "TCS",
        "Big Boss",
        "Asian Paints Colour World",
      ],
    },
    coursesAndFees: [
  // ─── UG COURSES ───
  {
    level: "UG",
    course: "BA",
    duration: "3 Years",
    totalFees: "₹1.0 – 1.1 Lakhs",
    perYearFees: "₹30,000 – 40,000/Year",
    eligibility: "10+2",
  },
  {
    level: "UG",
    course: "B.Com",
    duration: "3 Years",
    totalFees: "₹72,000 – 90,000",
    perYearFees: "₹25,000 – 30,000/Year",
    eligibility: "10+2",
  },
  {
    level: "UG",
    course: "B.Sc",
    duration: "3 Years",
    totalFees: "₹75,000 – 2.6 Lakhs",
    perYearFees: "₹25,000 – 90,000/Year",
    eligibility: "10+2 (Science)",
  },
  {
    level: "UG",
    course: "BCA",
    duration: "3 Years",
    totalFees: "₹1.27 Lakhs",
    perYearFees: "₹40,000 – 45,000/Year",
    eligibility: "10+2",
  },
  {
    level: "UG",
    course: "BBA",
    duration: "3 Years",
    totalFees: "₹1.27 Lakhs",
    perYearFees: "₹40,000 – 45,000/Year",
    eligibility: "10+2",
  },
  {
    level: "UG",
    course: "B.Ed",
    duration: "2 Years",
    totalFees: "₹1.0 Lakhs",
    perYearFees: "₹50,000/Year",
    eligibility: "Graduation",
  },

  // ─── OTHER UG ───
  {
    level: "UG",
    course: "B.Lib.I.Sc",
    duration: "1 Year",
    totalFees: "₹24,000",
    perYearFees: "₹24,000/Year",
    eligibility: "Graduation",
  },

  // ─── PG COURSES ───
  {
    level: "PG",
    course: "MA",
    duration: "2 Years",
    totalFees: "₹50,000",
    perYearFees: "₹25,000/Year",
    eligibility: "Graduation",
  },
  {
    level: "PG",
    course: "M.Com",
    duration: "2 Years",
    totalFees: "₹50,000",
    perYearFees: "₹25,000/Year",
    eligibility: "B.Com",
  }
]
  },

  {
    id: "Dibns",
    name: "DOLPHIN (PG) institute of biomedical and natural sciences",
    location: "Dehradun",
    image: "/img/Dolphin.webp",
    logo: "/img/DolphinLogo.jpg",
    rating: 4.3,
    brochure: "/brochures/Dolphin-brochure.pdf",
    desc: "Dolphin (PG) Institute of Biomedical & Natural Sciences is a private institute in Dehradun, established in 2002 and affiliated with HNB Garhwal University. It is mainly known for courses in biomedical, agriculture, and life sciences. The campus is green and peaceful with good labs and practical exposure, making it a decent option for science students. However, placements are average, so it’s better suited for students focusing on academics or higher studies.",
    cutoff: [
      {
        course: "B.Sc (Biotechnology / Microbiology / CS)",
        general: "50%",
        obc: "50%",
        sc: "45%",
        st: "45%",
      },
      {
        course: "B.Com",
        general: "45%",
        obc: "45%",
        sc: "40%",
        st: "40%",
      },
      {
        course: "BPT (Physiotherapy)",
        general: "50% (PCB)",
        obc: "50% (PCB)",
        sc: "45% (PCB)",
        st: "45% (PCB)",
      },
      {
        course: "M.Sc",
        general: "50% (Graduation)",
        obc: "50% (Graduation)",
        sc: "45% (Graduation)",
        st: "45% (Graduation)",
      },
      {
        course: "M.Com",
        general: "50% (Graduation)",
        obc: "45% (Graduation)",
        sc: "40% (Graduation)",
        st: "40% (Graduation)",
      },
    ],
    placement: {
      highlightStats: {
        highestPackage: "8-10 LPA",
        averagePackage: "4 LPA",
        medianPackage: "2 LPA",
        placementRate: "90%",
        studentsPlaced: "1847+",
        companiesVisited: "350+",
        year: "2024",
        note: "Biomedical & Life Sciences college — pharma, healthcare, agri sector placements",
      },
      branchWise: [
        {
          course: "M.Sc Biotechnology / Microbiology / Biochemistry",
          avgPackage: "4-5 LPA",
          highestPackage: "8-10 LPA",
          placedStudents: "90%",
          roles: "Research Scientist, Lab Analyst, QC Executive",
        },
        {
          course: "B.Sc Biotechnology / MLT / Microbiology",
          avgPackage: "3-4 LPA",
          highestPackage: "5.75 LPA",
          placedStudents: "85%",
          roles: "Lab Technician, Clinical Research, QA Associate",
        },
        {
          course: "B.Sc / M.Sc Agriculture & Horticulture",
          avgPackage: "3.5-5.5 LPA",
          highestPackage: "5.5 LPA",
          placedStudents: "90%",
          roles: "Agronomist, Agriculture Officer, ICAR Scientist",
        },
        {
          course: "MPT (Physiotherapy)",
          avgPackage: "3-4 LPA",
          highestPackage: "6 LPA",
          placedStudents: "85%",
          roles: "Physiotherapist, Rehab Specialist, Sports Therapist",
        },
        {
          course: "M.Sc Pharmaceutical Chemistry",
          avgPackage: "4-5 LPA",
          highestPackage: "8 LPA",
          placedStudents: "88%",
          roles: "Pharma Executive, Drug Inspector, R&D Analyst",
        },
      ],
      topRecruiters: [
        "Patanjali",
        "P&G",
        "Roche",
        "ITC",
        "Fresenius Kabi",
        "Intas Pharmaceuticals",
        "Themis Medicare",
        "GMP Pharmaceuticals",
        "Torrent Pharma",
        "Max Hospital",
        "Synergy Hospital",
        "Punjab Agro Venture",
        "Joshi Farms",
        "Ambrose Farms",
        "KVK Dehradun",
        "ICAR",
        "Dept. of Agriculture & Farmer Welfare",
      ],
    },
    coursesAndFees:[
  // ─── UG COURSES ───
  {
    level: "UG",
    course: "B.Sc",
    duration: "3–4 Years",
    totalFees: "₹3.0 – 3.6 Lakhs",
    perYearFees: "₹90,000 – 1.1 Lakh/Year",
    eligibility: "10+2 (PCB/PCM) with 45%",
  },
  {
    level: "UG",
    course: "B.Sc (Hons.)",
    duration: "4 Years",
    totalFees: "₹3.6 – 4.0 Lakhs",
    perYearFees: "₹90,000 – 1.2 Lakh/Year",
    eligibility: "10+2 (Science)",
  },
  {
    level: "UG",
    course: "BPT (Physiotherapy)",
    duration: "4–4.5 Years",
    totalFees: "₹2.8 – 4.4 Lakhs",
    perYearFees: "₹70,000 – 1.1 Lakh/Year",
    eligibility: "10+2 (PCB)",
  },
  {
    level: "UG",
    course: "B.Com",
    duration: "3 Years",
    totalFees: "₹1.8 Lakhs",
    perYearFees: "₹55,000 – 60,000/Year",
    eligibility: "10+2",
  },
  {
    level: "UG",
    course: "BBA (Hons.)",
    duration: "3–4 Years",
    totalFees: "₹3.5 – 3.6 Lakhs",
    perYearFees: "₹90,000/Year",
    eligibility: "10+2",
  },
  {
    level: "UG",
    course: "B.Ed",
    duration: "2 Years",
    totalFees: "₹1.7 Lakhs",
    perYearFees: "₹85,000/Year",
    eligibility: "Graduation",
  },

  // ─── PG COURSES ───
  {
    level: "PG",
    course: "M.Sc",
    duration: "2 Years",
    totalFees: "₹1.6 – 2.3 Lakhs",
    perYearFees: "₹80,000 – 1.2 Lakh/Year",
    eligibility: "B.Sc",
  },
  {
    level: "PG",
    course: "MPT",
    duration: "2 Years",
    totalFees: "₹1.6 – 2.3 Lakhs",
    perYearFees: "₹80,000 – 1.1 Lakh/Year",
    eligibility: "BPT",
  },
  {
    level: "PG",
    course: "MBA",
    duration: "2 Years",
    totalFees: "₹2.5 – 3.0 Lakhs",
    perYearFees: "₹1.2 – 1.5 Lakh/Year",
    eligibility: "Graduation",
  },          
  ],      
  },            
];  
  


export const exams = [
  {
    title: "CET 2026",
    image: "/img/cet.png",
    colleges: 30,
    date: "Feb 26, 2026",
    level: "Bachelors",
  },
  {
    title: "JEE 2026",
    image: "/img/jee.png",
    colleges: 50,
    date: "Jan 15, 2026",
    level: "Engineering",
  },
  {
    title: "NEET 2026",
    image: "/img/neet.jpg",
    colleges: 40,
    date: "May 10, 2026",
    level: "Medical",
  },
]

export const newsData = [
  {
    category: "Exam",
    date: "26th Feb 2026",
    title: "JEE Mains 2026 Exam Analysis ...",
    description:
      "It is a long established fact that a reader will be distracted...",
    icon: "/img/exam.jpg",
  },
  {
    category: "Courses",
    date: "26th Feb 2026",
    title: "Civil Engineering Courses ...",
    description:
      "It is a long established fact that a reader will be distracted...",
    icon: "/img/courses.png",
  },
  {
    category: "Exam",
    date: "26th Feb 2026",
    title: "JEE Mains 2026 Result Update ...",
    description:
      "It is a long established fact that a reader will be distracted...",
    icon: "/img/exam.jpg",
  },
];

export const PopularSearchData = [
  {
    title: "New Age Colleges",
    items: [
      "AI & Data Science Institutes",
      "FinTech Colleges",
      "Design & Creative Universities",
      "Sustainable Technology Schools",
    ],
  },
  {
    title: "Courses",
    items: [
      "B.Tech Computer Science",
      "MBA in Marketing",
      "Civil Engineering",
      "BCA & MCA Programs",
    ],
  },
  {
    title: "Entrance Exams",
    items: ["JEE Main", "NEET", "CUET", "CAT"],
  },
  {
    title: "Resources",
    items: [
      "Previous Year Papers",
      "Syllabus PDF",
      "College Comparison Tool",
      "Rank Predictor",
    ],
  },
  {
    title: "Tools & Predictor",
    items: ["College Predictor", "Exam Rank Predictor", "Fees Calculator"],
  },
  {
    title: "College Admission Forms",
    items: [
      "Apply to Top Colleges",
      "Track Application Status",
      "Scholarship Forms",
    ],
  },
];

export const features = [
  {
    title: "Accurate Results",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    icon: "/img/accurate.png",
    bg: "bg-yellow-100",
  },
  {
    title: "Personalized Recommendation",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    icon: "/img/personalized.png",
    bg: "bg-green-100",
  },
  {
    title: "Trusted By Thousand",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    icon: "/img/trusted.jpg",
    bg: "bg-orange-100",
  },
  {
    title: "Real Time Update",
    description:
      "It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.",
    icon: "/img/realTime.jpg",
    bg: "bg-pink-100",
  },
];

export const courseData = {
  UG: [
    {
      title: "BBA | Bachelor of Business Administration",
      duration: "3 Years",
      fees: "Rs. 1 - 1.5 Lakhs",
      colleges: 25,
    },
    {
      title: "BCA | Bachelor of Computer Applications",
      duration: "3 Years",
      fees: "Rs. 1.2 - 1.8 Lakhs",
      colleges: 20,
    },
  ],

  PG: [
    {
      title: "PGDM | Post Graduate Diploma Management",
      duration: "2 Years",
      fees: "Rs. 2 - 2.5 Lakhs",
      colleges: 30,
    },
    {
      title: "MBA | Master of Business Administration",
      duration: "2 Years",
      fees: "Rs. 2.5 - 3 Lakhs",
      colleges: 28,
    },
  ],

  Diploma: [
    {
      title: "Diploma in Engineering",
      duration: "3 Years",
      fees: "Rs. 80k - 1.2 Lakhs",
      colleges: 18,
    },
    {
      title: "Diploma in Pharmacy",
      duration: "2 Years",
      fees: "Rs. 90k - 1.3 Lakhs",
      colleges: 15,
    },
  ],
};
export const accreditations = [
  {
    title: "AICTE Approved",
    icon: "/img/accreditation.jpg",
  },
  {
    title: "NAAC Grade A+",
    icon: "/img/accreditation.jpg",
  },
  {
    title: "INI",
    icon: "/img/accreditation.jpg",
  },
];

export const facilities = [
  {
    title: "Academic Spaces",
    content:
      "Smart classrooms equipped with projectors, seminar halls, collaborative discussion rooms, and modern lecture theatres.",
  },
  {
    title: "Incubation Centers",
    content:
      "Startup incubation support, mentorship programs, innovation labs, and funding assistance for student entrepreneurs.",
  },
  {
    title: "Guest House",
    content:
      "Fully furnished guest rooms for visiting faculty, parents, and official guests with dining and lounge facilities.",
  },
  {
    title: "Laboratories",
    content:
      "Advanced labs for Mechanical, Civil, Computer Science, Physics, Chemistry, and Electronics with modern equipment.",
  },
  {
    title: "Library",
    content:
      "Digital library access, thousands of books, research journals, e-resources, and silent study zones.",
  },
  {
    title: "Medical Facilities",
    content:
      "On-campus health center with qualified doctors, emergency services, and first-aid assistance.",
  },
  {
    title: "Cafeteria",
    content:
      "Hygienic multi-cuisine cafeteria offering vegetarian and non-vegetarian meals at affordable prices.",
  },
  {
    title: "Hostels",
    content:
      "Separate boys and girls hostels with WiFi, 24/7 security, mess facilities, and recreational spaces.",
  },
  {
    title: "Auditorium",
    content:
      "Large fully air-conditioned auditorium for seminars, cultural events, workshops, and conferences.",
  },
  {
    title: "Student Help Desk",
    content:
      "Dedicated student support center for academic queries, documentation, grievance redressal, and guidance.",
  },
  {
    title: "Transport Service",
    content:
      "University-operated bus services covering major city routes with safety and punctuality.",
  },
];
export const AddmissionProcessesData = [
  {
    title: "Entrance Exam",
    icon: "/img/exam1.jpg",
    content:
      "Candidates must appear for JEE Main or university entrance examination. Selection is based on merit and exam performance.",
  },
  {
    title: "Cutoff & Shortlisting",
    icon: "/img/cutoff.jpg",
    content:
      "Based on exam results, cutoff marks are released. Eligible candidates are shortlisted for counseling and document verification.",
  },
  {
    title: "Final Admission",
    icon: "/img/admission.png",
    content:
      "After verification and fee submission, final admission confirmation is granted. Students receive enrollment details.",
  },
];

export const KeyhighlightsData = [
  {
    title: "Courses :",
    value: "45+",
    icon: "/img/courses1.jpg",
  },
  {
    title: "Avg Fees :",
    value: "Rs. 2.4 L/Year",
    icon: "/img/fees.jpg",
  },
  {
    title: "Total Seat :",
    value: "1535",
    icon: "/img/seats.jpg",
  },
  {
    title: "Campus :",
    value: "120 Acres",
    icon: "/img/campus.jpg",
  },
];
export const reviewsData = [
  {
    rating: 4.5,
    quote: "Great placement and supportive faculty",
    name: "Rahul S.",
    course: "B.Tech CSE",
    batch: "2025 Batch",
  },
  {
    rating: 4.5,
    quote: "Excellent campus life and exposure",
    name: "Ananya K.",
    course: "B.Tech IT",
    batch: "2024 Batch",
  },
  {
    rating: 4.5,
    quote: "Good infrastructure and labs",
    name: "Vikram P.",
    course: "Mechanical Engineering",
    batch: "2023 Batch",
  },
];

export const CoursesSectionData = {
  UG: [
    {
      title: "Bachelor Of Technology ( B. Tech )",
      specs: [
        "B.Tech in Information Technology",
        "B.Tech in Aerospace Engineering",
        "B.Tech in Mechanical Engineering",
      ],
    },
    {
      title: "Bachelor Of Science",
      specs: [
        "Bachelor of Science in Physics",
        "Bachelor of Science in Chemistry",
        "Bachelor of Science in Maths",
      ],
    },
    {
      title: "Bachelor Of Technology ( B. Tech )",
      specs: [
        "B.Tech in Information Technology",
        "B.Tech in Aerospace Engineering",
        "B.Tech in Mechanical Engineering",
      ],
    },
  ],
  PG: [
    {
      title: "Master Of Technology ( M.Tech )",
      specs: [
        "M.Tech in Civil Engineering",
        "M.Tech in Computer Science",
        "M.Tech in Electrical Engineering",
      ],
    },
  ],
  Diploma: [
    {
      title: "Diploma in Engineering",
      specs: [
        "Diploma in Mechanical",
        "Diploma in Civil",
        "Diploma in Electrical",
      ],
    },
  ],
};
